// server.js
const next = require('next');
const https = require('https');
const fs = require('fs');
const path = require('path');

const port = parseInt(process.env.PORT || '3000', 10);

// paths to your SSL certificate and key generated by mkcert
// these should be in the project root or a known directory
const sslDirectory = process.cwd(); // Assuming certs are in the project root
const sslKeyPath = path.join(sslDirectory, 'localhost-key.pem');
const sslCertPath = path.join(sslDirectory, 'localhost.pem'); // mkcert usually creates localhost.pem and localhost-key.pem

const dev = process.env.NODE_ENV !== 'production';

const app = next({
  dev,
  conf: {
    // your next.config.js options can be passed here if needed
    // For example:
    // distDir: '.next',
    // output: process.env.NEXT_BUILD_STANDALONE ? 'standalone' : undefined,
    // allowedDevOrigins: ['*'], // Already handled in next.config.ts
  },
});

const handle = app.getRequestHandler();

app.prepare().then(() => {
  let serverOptions = {};
  try {
    // Check if certificate files exist
    if (fs.existsSync(sslKeyPath) && fs.existsSync(sslCertPath)) {
      serverOptions = {
        key: fs.readFileSync(sslKeyPath),
        cert: fs.readFileSync(sslCertPath),
      };
      console.log('Using SSL certificates for HTTPS.');
    } else {
      console.warn('SSL certificates not found. Falling back to HTTP. Please generate certificates using mkcert.');
      console.warn(`Expected files: ${sslKeyPath}, ${sslCertPath}`);
      // If certs are not found, https server will fail.
      // For simplicity, we could fall back to http, but the goal is HTTPS.
      // So we will throw an error if certs are missing.
      throw new Error('SSL certificates not found.');
    }
  } catch (error) {
    console.error('Error loading SSL certificates:', error);
    // Exit if SSL is required and certificates are missing
    process.exit(1);
  }

  https.createServer(serverOptions, (req, res) => {
    handle(req, res);
  }).listen(port, (err) => {
    if (err) throw err;
    console.log(`> Ready on https://localhost:${port}`);
    console.log(`> Ensure your application is accessible via https://${process.env.APP_URL_HOSTNAME || 'localhost'}:${port}`);
  });
});
